### ISSUE TITLE
Error API Access

### ISSUE THREAD

**Issue by tcelestino** [brpaz/ulauncher-currency#4]
When I've attempted to convert currency, this is happening:

![screenshot from 2019-02-06 12-54-48](https://user-images.githubusercontent.com/190265/52349908-9c32e280-2a0e-11e9-90b1-4b61203b8c17.jpg)

**Comment by SonephetR2** [comment]
Hi,
Have you supplier a Fixer API in Ulauncher's preferences > Extensions tab?
Regards,

**Comment by tcelestino** [comment]
> Hi,
> Have you supplier a Fixer API in Ulauncher's preferences > Extensions tab?
> Regards,

No. I've installed the extension via uLauncher website and there's not about that information. I read README.md and I found it. I will close this issues. 

Thanks @SonephetR2
