### ISSUE TITLE
Error click on link to get API Key

### ISSUE THREAD

**Issue by tcelestino** [brpaz/ulauncher-currency#5]
When it click on link to get a key to Fixer.io API, the website is opening in the same ULauncher's window. 

![screenshot from 2019-02-26 17-19-59](https://user-images.githubusercontent.com/190265/53443785-358c5d80-39eb-11e9-9c10-9aee3888daad.png)

I was looking for in other links (eg.: link to repo) and every links to open in the browsers window.

**Comment by brpaz** [comment]
I removed the link as it seems, I can´t properly create an external link, You can find the link in the README.
