### ISSUE TITLE
Port extension to Ulauncher 5

### ISSUE THREAD

**Issue by vipau** [brpaz/ulauncher-currency#7]
Ulauncher 5 (of which development builds are already available) will ship the Python 3 version only. As a result, all extensions have to be ported to Python 3, and also the new Ulauncher Extension API v2.

See [more details here](http://docs.ulauncher.io/en/latest/extensions/migration.html#migrate-from-api-v1-to-v2-0-0)

**Comment by brpaz** [comment]
Hi. Thanks for the heads up!  Didn't know there were already builds for the Python 3 version.  Yes, I will hope to migrate all my extensions to Python 3.

**Comment by brunoais** [comment]
@brpaz Any updates? This extension has stopped working for me for a while

**Comment by brpaz** [comment]
It should work now with the latest Ulauncher versions
